version: '3.1'

services:
  quierolotedb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: z3DC8Pbv89M9pAgr
    container_name: quierolote-database
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
