
import { HeaderAdmin } from '@/components/composites/HeaderAdmin/HeaderAdmin';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function GeneralLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <HeaderAdmin />
      {children}
    </>
  );
}
