import { Header } from '@/components/composites/Header/Header';
import { Footer } from '@/components/composites/footer/Footer';
import { GeneralThemeProvider } from '@/context/themeContext/GeneralThemeProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <GeneralThemeProvider>
          <Header />
          {children}
          <Footer />
        </GeneralThemeProvider>
      </body>
    </html>
  );
}
